//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganikUrunZincirTakip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Depolama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Depolama()
        {
            this.Nakliyes = new HashSet<Nakliye>();
        }
    
        public int DepolamaID { get; set; }
        public int DenetlemeID { get; set; }
        public string DepolamaYer { get; set; }
        public System.DateTime DepolamaTarih { get; set; }
        public string DepolamaAcıklama { get; set; }
        [DisplayName("Depolayıcı")]
        public int UserId { get; set; }
    
        public virtual Denetleme Denetleme { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nakliye> Nakliyes { get; set; }
    }
}
