//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganikUrunZincirTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nakliye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nakliye()
        {
            this.Satis = new HashSet<Sati>();
        }
    
        public int NakliyeID { get; set; }
        public int DepolamaID { get; set; }
        public string TeslimalimYer { get; set; }
        public string TeslimedimYer { get; set; }
        public System.DateTime Tarih { get; set; }
        public string NakliyeAcıklama { get; set; }
        public int UserId { get; set; }
    
        public virtual Depolama Depolama { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sati> Satis { get; set; }
    }
}
